### ISSUE TITLE
Pulling 0 byte file freezes the extension

### ISSUE THREAD

**Issue by Zaczero** [mkloubert/vscode-deploy-reloaded#82]
### Description

While testing the #64 bug I've noticed that pulling 0 byte file (0 byte on remote) freezes the extension.

### Actual behavior

Extension freezes and you have to restart the vscode.

### Expected behavior

Extension doesn't freeze and the file gets pulled successfully.

### Steps to reproduce

1. Create file with 0b size *(let's call it hello.txt)* in vscode (local)
2. Deploy the file to the remote
3. Pull the file from remote

#### Example config

```json
{
    "deploy.reloaded": {
        "packages": [
            {
                "button": {
                    "text": "Deploy",
                    "targets": [
                        "target_ftp",
                    ],
                }
            }
        ],
        "targets": [
            {
                "name": "target_ftp",

                "type": "sftp",
                "dir": "***",

                "host": "***",
                "user": "***",
                "privateKey": "***",
                "askForPrivateKeyPassphrase": true,
            }
        ],
    }
}
```

#### Logs

```
INFO extension.deploy.reloaded.loadplugins - [24/Jun/2018:18:16:23 +0000] "Loaded 19 plugins:
- app
- azureblob
- batch
- compiler
- dropbox
- each
- ftp
- list
- local
- mail
- map
- prompt
- s3bucket
- script
- sftp
- slack
- switch
- test
- zip
"
```

#### Screenshot

![](https://prtsc.me/i/24a4c52b.jpeg)
🕐 🕥 🕙 

### Your environment

Operating system: Windows 10 Pro 17134
Visual Studio Code version: 1.24.1
Extension version: 0.81.1

### Additional comments

The **Cancel** button on the notification pop-up doesn't work with single file and you are forced to restart the vscode (reload?).  
Deploy of 0 byte file works fine.

**Comment by mkloubert** [comment]
@Zaczero 

**The bug should be fixed since version 0.81.2.**

I have downgraded the [ssh2-sftp-client](https://www.npmjs.com/package/ssh2-sftp-client) module back to `2.2.1`.

**Comment by cuiyang000** [comment]
It's still not working with the latest version 0.87.2

**Comment by clevend2** [comment]
Reporting that if there are any 0 byte files on my destination, a pull w/ subfolders will hang on those files.  Have to manually remove them so deploy doesn't try to get them. Also on 0.87.2

**Comment by pdrharris** [comment]
Hello,
I am still experiencing this issue - pulling hangs indefinitely on 0 byte files (__init__.py)
Expected behaviour: Pulling a folder / package
Actual behaviour: Hangs indefinitely on 0 byte file.

VS Code info:
Version: 1.40.1 (system setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Deploy Reloaded v. 0.89.0

Config:

        "packages": [
            {
                "name": "Onconet_Public",
                "description": "Onconet_Public",
                "files": ["/**/*"],
                "exclude": ["*.pyc"],
                "deployOnSave": ["GCloud-2"]
            }
        ],

        "targets": [
            {
                "type": "sftp",
                "name": "GCloud-2",
                "description": "SFTP folder on GCloud-2",
                "host": "*****", "port": 22,
                "user": "*****",
                "privateKey": "****",
                "dir": "****"
            }
